# Generated by Django 4.0.5 on 2022-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ustensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cook_time', models.DurationField()),
                ('prep_time', models.DurationField()),
                ('perform_time', models.DurationField()),
                ('total_time', models.DurationField()),
                ('created', models.DateField()),
                ('modified', models.DateField()),
                ('ingredients', models.ManyToManyField(to='back.ingredient')),
                ('steps', models.ManyToManyField(to='back.recipestep')),
                ('ustensils', models.ManyToManyField(to='back.ustensil')),
            ],
        ),
    ]
