# Generated by Django 4.0.5 on 2023-01-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ustensils',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ustensils',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeStep',
        ),
        migrations.DeleteModel(
            name='Ustensil',
        ),
    ]
