# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "1925300a0fe4cc9fc3985910bb04ae65a19ce274dacc5ec76e708cfa87a7952a0a77282b083d0aebb2206afff619af73a57f0d661a3423601586f0829cc7956b";
      version = "1.11.1";

    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "f521f95b362a47bb35f7c85528c34537f905fb3dd24f2284201e445635a0df701b35d8419d53c6507cc78d3717c1f83cda35ea4c82abd8943cd2ab3de3fcad70";
      version = "0.2.62";

    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "ddfe4fa84622abd8ac56e2aa565a56e6bdc0bf330f377ff3e269ddc241bb9dbcac332c13502dfd4c09c2c08fe24d8d2e8cf3d04a1bc819ca5657b4e41feaa7c2";
      version = "0.3.218";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-cbor/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-cbor";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "b6e16c43fb3e71f82f8e7dc558f53cbcc8fea31efa59f40d22220f6e40167cf32c150efa18a81f839008d6a042e201bf17d8fd52a4fecbe8f356454f2d6a6170";
      version = "2.13.3";

    };
    paths = [ src ];
  }

  rec {
    name = "depstar/seancorfield";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "depstar";
      groupId = "seancorfield";
      sha512 = "0f4458b39b8b1949755bc2fe64b239673a9efa3a0140998464bbbcab216ec847344c1b8920611f7c9ca07261850f3a08144ae221cc2c41813a080189e32f9c10";
      version = "1.0.94";

    };
    paths = [ src ];
  }

  rec {
    name = "ordered/org.flatland";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "ordered";
      groupId = "org.flatland";
      sha512 = "676db4c71999127822349f5f97960115aa5f3124eb3a93b441680c5ba747ebc1981718f93e8dc94fe34f0c1c84ea3568c452691967b92509e5e125dac3ee59eb";
      version = "1.5.9";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "d5337db908b2c56dcb911e3d1a5f671456c13f254fe8d2a620823bc15b2db6aaa8325a86b436b5d181f2584b533158fd14d140b98305ac252f8dfd9a627da859";
      version = "2.13.3";

    };
    paths = [ src ];
  }

  rec {
    name = "snakeyaml/org.yaml";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "snakeyaml";
      groupId = "org.yaml";
      sha512 = "787b72aebb685689ab379ed8f238fc2f4175bb82d285909e39e7ff1ee1b9e64ad8878f4685dadde274f950b0dc77dca3082a52921c11094aa2a535672ae4f33c";
      version = "1.33";

    };
    paths = [ src ];
  }

  rec {
    name = "clj-yaml/clj-commons";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-yaml";
      groupId = "clj-commons";
      sha512 = "5aae1b75426c433464064cb0d4eb9373009b5a1bdf032eb4224d2876b8aa7a27f69dd9078465f95c1e3b25233b7cfbd3098339efce4691380dec1dd92e4e4d8c";
      version = "1.0.26";

    };
    paths = [ src ];
  }

  rec {
    name = "cheshire/cheshire";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "cheshire";
      groupId = "cheshire";
      sha512 = "2262573047d194bba28b3d2ca4b00b12f8171d6f8f7f5449df35f10ab1ef5902a9ba2f9937399d6e4b54a78bda919fa205a22a44cde998019bc0cfc508e90f29";
      version = "5.11.0";

    };
    paths = [ src ];
  }

  rec {
    name = "tigris/tigris";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tigris";
      groupId = "tigris";
      sha512 = "fdff4ef5e7175a973aaef98de4f37dee8e125fc711c495382e280aaf3e11341fe8925d52567ca60f3f1795511ade11bc23461c88959632dfae3cf50374d02bf6";
      version = "0.1.2";

    };
    paths = [ src ];
  }

  rec {
    name = "fs/babashka";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "fs";
      groupId = "babashka";
      sha512 = "d1c8ade51aa39eeb594fae373dd35074173a237a3f50b105b1b453e9418a659acf3775ba07ee13ab3ef6c2c28cf8d7b766e49a14296eeb57e790c0f8ee58d216";
      version = "0.2.16";

    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-smile/com.fasterxml.jackson.dataformat";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-smile";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "4c1566aa4fac309de8fba08ea355165cf2a888b7bcec98e7035ac8acd7315e340415a10b8deec6497fc4eea5ba9319fc989676170d8c4c0d0bbc3d4f3cc4d681";
      version = "2.13.3";

    };
    paths = [ src ];
  }

  ];
  }
  