# Generated by Django 4.0.5 on 2022-07-05 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_cardtag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sm2_easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='sm2_interval',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='sm2_repetition_number',
            field=models.IntegerField(default=0),
        ),
    ]
