# Generated by Django 4.0.5 on 2022-07-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_card_sm2_easiness_factor_card_sm2_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='sm2_interval',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TestWorkflowQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='back.card')),
                ('test_workflow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='back.testworkflow')),
            ],
        ),
    ]
