# Generated by Django 4.0.5 on 2022-07-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_testworkflow_alter_card_sm2_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='sm2_interval',
            new_name='sm2_next_date',
        ),
    ]
