# Generated by Django 4.0.5 on 2022-07-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_rename_sm2_interval_card_sm2_next_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestWorkflowQuestions',
            new_name='TestWorkflowQuestion',
        ),
    ]
