# Generated by Django 4.0.5 on 2022-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_card_sm2_interval_testworkflowquestion_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sm2_next_date',
            field=models.DateField(),
        ),
    ]
