# Generated by Django 4.0.5 on 2022-07-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_alter_card_sm2_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.card'),
        ),
    ]
