# Generated by Django 4.0.5 on 2022-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_rename_testworkflowquestions_testworkflowquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sm2_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testworkflowquestion',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
