# Generated by Django 4.0.5 on 2022-07-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_alter_cardtag_card_alter_testworkflowquestion_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.card'),
        ),
    ]
