##
# Trie C++
#

CXX := g++

CXXFLAGS := -std=c++20 -pedantic -Wall -Wextra -fsanitize=address -g3 -ggdb
#CXXFLAGS += -Werror

.PHONY: clean
clean:
	@rm -rf trie.o trie

.PHONY: test
test: trie
	./trie

# end
